/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.modules.admin.importer;

/**
 *
 * @author Josep
 */
public class ImporterTest extends org.iesapp.framework.pluggable.DockingFrameworkApp {

    /**
     * Creates new form FitxesApp
     */
    public ImporterTest(String[] args) {
        super(args);
        this.appNameId="importer";
        this.appDisplayName="Importador";
        this.appDescription="Importador de medicaments i alumnat NESE";
        initComponents();
        this.appClass = getClass();
        this.requiredJar = "org-iesapp-modules-admin-importer.jar";
        this.requiredModuleName  = "org.iesapp.modules.admin.importer.MedicamentsModule";       
        this.initializeFramework();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


     public static void main(String[] args) {
         ImporterTest fitxesApp = new ImporterTest(args);
         fitxesApp.setVisible(true);

        
    }
}
